# SPDX-FileCopyrightText: The openTCS Authors
# SPDX-License-Identifier: CC-BY-4.0

# This file contains default configuration values and should not be modified.
# To adjust the application configuration, override values in a separate file.

bff.bindAddress = 0.0.0.0
bff.bindPort = 8090

bff.security.accessKey =

bff.kernel.host = localhost
bff.kernel.port = 1099
bff.kernel.userName = Alice
bff.kernel.password = xyz
